/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_f7b587fc (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/lajgxkcqnqmgzofshqdg/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => {
  const url = Deno.env.get("SUPABASE_URL") || "https://lajgxkcqnqmgzofshqdg.supabase.co";
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "sb_secret_Mduz02x72HYd96_taiK2ww_1YlIiZib";
  console.log("[KV] Creating client with URL:", url);
  return createClient(url, key);
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  try {
    console.log("[KV] Setting key:", key);
    const supabase = client()
    const { error } = await supabase.from("kv_store_f7b587fc").upsert({
      key,
      value
    });
    if (error) {
      console.error("[KV] Set error:", error);
      throw new Error(error.message);
    }
    console.log("[KV] Successfully set key:", key);
  } catch (e) {
    console.error("[KV] Set exception:", e);
    throw e;
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  try {
    console.log("[KV] Getting key:", key);
    const supabase = client()
    const { data, error } = await supabase.from("kv_store_f7b587fc").select("value").eq("key", key).maybeSingle();
    if (error) {
      console.error("[KV] Get error:", error);
      throw new Error(error.message);
    }
    console.log("[KV] Successfully got key:", key, "Data:", !!data);
    return data?.value;
  } catch (e) {
    console.error("[KV] Get exception:", e);
    throw e;
  }
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  try {
    console.log("[KV] Deleting key:", key);
    const supabase = client()
    const { error } = await supabase.from("kv_store_f7b587fc").delete().eq("key", key);
    if (error) {
      console.error("[KV] Delete error:", error);
      throw new Error(error.message);
    }
    console.log("[KV] Successfully deleted key:", key);
  } catch (e) {
    console.error("[KV] Delete exception:", e);
    throw e;
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_f7b587fc").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_f7b587fc").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_f7b587fc").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_f7b587fc").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};